version: '3.8'

services:
  terminusdb:
    image: terminusdb/terminusdb-server:latest
    container_name: terminusdb
    environment:
      - TERMINUSDB_SERVER_NAME=oms-terminusdb
      - TERMINUSDB_ADMIN_PASS=admin
      - TERMINUSDB_SERVER_PORT=6363
      - TERMINUSDB_AUTOLOGIN=true
    ports:
      - "6363:6363"
    volumes:
      - terminusdb-data:/app/storage
    networks:
      - oms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6363/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  oms-network:
    external: true
    name: arrakis-project_oms-network

volumes:
  terminusdb-data: