version: '3.8'

services:
  # Redis for job queue and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main API server
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TERMINUSDB_ENDPOINT=${TERMINUSDB_ENDPOINT:-http://terminusdb:6363}
      - WORKER_MODE=false
    volumes:
      - .:/app
    depends_on:
      - redis
      - terminusdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        echo 'Starting API server...' &&
        uvicorn bootstrap.app:create_app --host 0.0.0.0 --port 8000 --reload
      "

  # Celery worker for background jobs
  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TERMINUSDB_ENDPOINT=${TERMINUSDB_ENDPOINT:-http://terminusdb:6363}
      - WORKER_MODE=true
    volumes:
      - .:/app
    depends_on:
      - redis
      - terminusdb
      - api
    healthcheck:
      test: ["CMD", "celery", "-A", "workers.celery_app", "inspect", "ping"]
      interval: 60s
      timeout: 30s
      retries: 3
    command: >
      sh -c "
        echo 'Waiting for API to be ready...' &&
        sleep 30 &&
        echo 'Starting Celery worker...' &&
        celery -A workers.celery_app worker --loglevel=info --concurrency=4
      "

  # Celery beat for scheduled tasks
  beat:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TERMINUSDB_ENDPOINT=${TERMINUSDB_ENDPOINT:-http://terminusdb:6363}
      - WORKER_MODE=true
    volumes:
      - .:/app
    depends_on:
      - redis
    command: >
      sh -c "
        echo 'Starting Celery beat...' &&
        celery -A workers.celery_app beat --loglevel=info
      "

  # Flower for monitoring Celery
  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
    command: >
      sh -c "
        echo 'Starting Flower...' &&
        celery -A workers.celery_app flower --port=5555
      "

  # TerminusDB
  terminusdb:
    image: terminusdb/terminusdb-server:latest
    ports:
      - "6363:6363"
    volumes:
      - terminusdb_data:/app/terminusdb/storage
    environment:
      - TERMINUSDB_ADMIN_PASSWD=admin
      - TERMINUSDB_SERVER_NAME=terminusdb
      - TERMINUSDB_SERVER_PORT=6363
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6363/api/info"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Nginx for load balancing (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    profiles: ["production"]

volumes:
  redis_data:
  terminusdb_data: