global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'oms-cluster'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # OMS Monolith
  - job_name: 'oms-monolith'
    static_configs:
      - targets: ['oms-monolith:8091']
        labels:
          service: 'oms-monolith'
          type: 'api'

  # Data-Kernel Gateway
  - job_name: 'data-kernel'
    static_configs:
      - targets: ['data-kernel:8080']
        labels:
          service: 'data-kernel'
          type: 'gateway'

  # Microservices
  - job_name: 'embedding-service'
    static_configs:
      - targets: ['embedding-service:8001']
        labels:
          service: 'embedding-service'
          type: 'microservice'

  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:8002']
        labels:
          service: 'scheduler-service'
          type: 'microservice'

  - job_name: 'event-gateway'
    static_configs:
      - targets: ['event-gateway:8003']
        labels:
          service: 'event-gateway'
          type: 'microservice'

  # Infrastructure
  - job_name: 'terminusdb'
    static_configs:
      - targets: ['terminusdb:6363']
        labels:
          service: 'terminusdb'
          type: 'database'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres'
          type: 'database'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'
          type: 'cache'

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
        labels:
          service: 'nats'
          type: 'messaging'

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: 'jaeger'
          type: 'tracing'