name: Schema Generation Smoke Test

on:
  pull_request:
    paths:
      - 'models/domain.py'
      - 'models/semantic_types.py'
      - 'models/struct_types.py'
      - 'core/api/schema_generator.py'
      - 'api/v1/schema_generation/**'
      - 'tests/test_schema_generator.py'

jobs:
  schema-generation-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Need full history for diff
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install deepdiff pyyaml
    
    - name: Generate baseline schemas (main branch)
      run: |
        git checkout main
        python -m scripts.generate_schemas --dry-run --output-dir /tmp/baseline
        
    - name: Generate PR schemas
      run: |
        git checkout ${{ github.head_ref }}
        python -m scripts.generate_schemas --dry-run --output-dir /tmp/pr
    
    - name: Compare schemas
      run: |
        python -m scripts.compare_schemas /tmp/baseline /tmp/pr --format json > schema_diff.json
        
    - name: Check structural differences
      run: |
        python -c "
        import json
        import sys
        
        with open('schema_diff.json', 'r') as f:
            diff = json.load(f)
        
        # Check GraphQL differences
        graphql_diff = diff.get('graphql', {})
        if graphql_diff.get('structural_changes', 0) > 0:
            print('❌ GraphQL schema has structural changes:')
            for change in graphql_diff.get('changes', []):
                print(f'  - {change}')
            sys.exit(1)
        
        # Check OpenAPI differences  
        openapi_diff = diff.get('openapi', {})
        if openapi_diff.get('structural_changes', 0) > 0:
            print('❌ OpenAPI schema has structural changes:')
            for change in openapi_diff.get('changes', []):
                print(f'  - {change}')
            sys.exit(1)
            
        print('✅ No structural differences in generated schemas')
        "
    
    - name: Upload diff report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: schema-diff-report
        path: |
          schema_diff.json
          /tmp/baseline/
          /tmp/pr/
    
    - name: Comment PR with results
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          
          let comment = '## 📋 Schema Generation Test Results\n\n';
          
          try {
            const diff = JSON.parse(fs.readFileSync('schema_diff.json', 'utf8'));
            
            if (diff.graphql.structural_changes === 0 && diff.openapi.structural_changes === 0) {
              comment += '✅ **All tests passed!** No structural changes detected.\n';
            } else {
              comment += '❌ **Schema changes detected!**\n\n';
              
              if (diff.graphql.structural_changes > 0) {
                comment += '### GraphQL Changes\n';
                diff.graphql.changes.forEach(change => {
                  comment += `- ${change}\n`;
                });
                comment += '\n';
              }
              
              if (diff.openapi.structural_changes > 0) {
                comment += '### OpenAPI Changes\n';
                diff.openapi.changes.forEach(change => {
                  comment += `- ${change}\n`;
                });
              }
            }
            
            // Performance metrics
            if (diff.performance) {
              comment += '\n### Performance Metrics\n';
              comment += `- GraphQL generation: ${diff.performance.graphql_ms}ms\n`;
              comment += `- OpenAPI generation: ${diff.performance.openapi_ms}ms\n`;
            }
            
          } catch (error) {
            comment += '⚠️ Error analyzing schema differences. Check artifacts for details.\n';
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run schema generator tests
      run: |
        pytest tests/test_schema_generator.py -v --cov=core.api.schema_generator
        
    - name: Check test coverage
      run: |
        coverage report --fail-under=90