[tool.poetry]
name = "common-rate-limiting"
version = "1.0.0"
description = "Unified rate limiting utilities for all services"
authors = ["Arrakis Team <team@arrakis.dev>"]
packages = [{include = "common_rate_limiting"}]

[tool.poetry.dependencies]
python = "^3.9"
redis = {version = "^5.0.0", extras = ["asyncio"]}
fastapi = {version = "^0.100.0", optional = true}
starlette = {version = "^0.27.0", optional = true}

[tool.poetry.extras]
fastapi = ["fastapi", "starlette"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.0.0"
black = "^23.0.0"
ruff = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"