#!/bin/bash
# Recovery script for archived files
# Generated on 2025-07-04T20:39:30.469110

echo "🔄 Recovering 73 files from archive..."

mv "archive_legacy_20250704/api/auth_examples.py" "api/auth_examples.py" 2>/dev/null
mv "archive_legacy_20250704/api/gateway/graphql_proxy.py" "api/gateway/graphql_proxy.py" 2>/dev/null
mv "archive_legacy_20250704/api/graphql/working_schema.py" "api/graphql/working_schema.py" 2>/dev/null
mv "archive_legacy_20250704/bootstrap/database_config.py" "bootstrap/database_config.py" 2>/dev/null
mv "archive_legacy_20250704/check_imports.py" "check_imports.py" 2>/dev/null
mv "archive_legacy_20250704/config/circuit_breaker_secure.py" "config/circuit_breaker_secure.py" 2>/dev/null
mv "archive_legacy_20250704/core/action/dlq_handler.py" "core/action/dlq_handler.py" 2>/dev/null
mv "archive_legacy_20250704/core/audit/database_interface.py" "core/audit/database_interface.py" 2>/dev/null
mv "archive_legacy_20250704/core/audit/sidecar_validator.py" "core/audit/sidecar_validator.py" 2>/dev/null
mv "archive_legacy_20250704/core/auth/resource_permission_checker.py" "core/auth/resource_permission_checker.py" 2>/dev/null
mv "archive_legacy_20250704/core/branch/foundry_branch_service.py" "core/branch/foundry_branch_service.py" 2>/dev/null
mv "archive_legacy_20250704/core/event_consumer/iam_event_handler.py" "core/event_consumer/iam_event_handler.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/change_detector.py" "core/events/backends/change_detector.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/cloudevents_adapter.py" "core/events/backends/cloudevents_adapter.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/cloudevents_migration.py" "core/events/backends/cloudevents_migration.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/enhanced_event_service.py" "core/events/backends/enhanced_event_service.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/eventbridge_adapter.py" "core/events/backends/eventbridge_adapter.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/nats_backend.py" "core/events/backends/nats_backend.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/nats_config.py" "core/events/backends/nats_config.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/nats_publisher.py" "core/events/backends/nats_publisher.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/outbox_processor.py" "core/events/backends/outbox_processor.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/outbox_service.py" "core/events/backends/outbox_service.py" 2>/dev/null
mv "archive_legacy_20250704/core/events/backends/state_store.py" "core/events/backends/state_store.py" 2>/dev/null
mv "archive_legacy_20250704/core/graph/index_generator.py" "core/graph/index_generator.py" 2>/dev/null
mv "archive_legacy_20250704/core/merge/unified_merge.py" "core/merge/unified_merge.py" 2>/dev/null
mv "archive_legacy_20250704/core/scheduler/advanced_scheduler.py" "core/scheduler/advanced_scheduler.py" 2>/dev/null
mv "archive_legacy_20250704/core/schema_generator/asyncapi_generator.py" "core/schema_generator/asyncapi_generator.py" 2>/dev/null
mv "archive_legacy_20250704/core/schema_generator/graphql_to_asyncapi.py" "core/schema_generator/graphql_to_asyncapi.py" 2>/dev/null
mv "archive_legacy_20250704/core/schema_generator/sdk_generator.py" "core/schema_generator/sdk_generator.py" 2>/dev/null
mv "archive_legacy_20250704/core/time_travel/db_optimizations.py" "core/time_travel/db_optimizations.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/ci_integration.py" "core/validation/ci_integration.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/input_sanitization.py" "core/validation/input_sanitization.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/migration_planner.py" "core/validation/migration_planner.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/naming_convention_v2.py" "core/validation/naming_convention_v2.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/rules/data_impact_analyzer.py" "core/validation/rules/data_impact_analyzer.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/rules/example_decorated_rule.py" "core/validation/rules/example_decorated_rule.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/rules/naming_convention_rule.py" "core/validation/rules/naming_convention_rule.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/rules/primary_key.py" "core/validation/rules/primary_key.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/rules/required_field.py" "core/validation/rules/required_field.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/rules/shared_property.py" "core/validation/rules/shared_property.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/rules/type_incompatibility.py" "core/validation/rules/type_incompatibility.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/tampering_detection.py" "core/validation/tampering_detection.py" 2>/dev/null
mv "archive_legacy_20250704/core/validation/validation_logging.py" "core/validation/validation_logging.py" 2>/dev/null
mv "archive_legacy_20250704/core/versioning/merge_engine_fix.py" "core/versioning/merge_engine_fix.py" 2>/dev/null
mv "archive_legacy_20250704/infra/siem/serializer.py" "infra/siem/serializer.py" 2>/dev/null
mv "archive_legacy_20250704/infrastructure/aws/cloudwatch_alarms.py" "infrastructure/aws/cloudwatch_alarms.py" 2>/dev/null
mv "archive_legacy_20250704/infrastructure/aws/eventbridge_rules.py" "infrastructure/aws/eventbridge_rules.py" 2>/dev/null
mv "archive_legacy_20250704/infrastructure/aws/eventbridge_setup.py" "infrastructure/aws/eventbridge_setup.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/common/redis_utils.py" "middleware/common/redis_utils.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/component_middleware.py" "middleware/component_middleware.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/coordinator.py" "middleware/coordinator.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/discovery/balancer.py" "middleware/discovery/balancer.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/discovery/coordinator.py" "middleware/discovery/coordinator.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/dlq/coordinator.py" "middleware/dlq/coordinator.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/dlq/deduplicator.py" "middleware/dlq/deduplicator.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/dlq/detector.py" "middleware/dlq/detector.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/etag_middleware.py" "middleware/etag_middleware.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/event_state_store.py" "middleware/event_state_store.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/health/coordinator.py" "middleware/health/coordinator.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/health/monitor.py" "middleware/health/monitor.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/issue_tracking_middleware.py" "middleware/issue_tracking_middleware.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/rate_limiting/coordinator.py" "middleware/rate_limiting/coordinator.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/rate_limiting/limiter.py" "middleware/rate_limiting/limiter.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/schema_freeze_middleware.py" "middleware/schema_freeze_middleware.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/service_config.py" "middleware/service_config.py" 2>/dev/null
mv "archive_legacy_20250704/middleware/three_way_merge.py" "middleware/three_way_merge.py" 2>/dev/null
mv "archive_legacy_20250704/models/function_types.py" "models/function_types.py" 2>/dev/null
mv "archive_legacy_20250704/models/override_request.py" "models/override_request.py" 2>/dev/null
mv "archive_legacy_20250704/sdks/python/setup.py" "sdks/python/setup.py" 2>/dev/null
mv "archive_legacy_20250704/shared/cache/terminusdb_cache.py" "shared/cache/terminusdb_cache.py" 2>/dev/null
mv "archive_legacy_20250704/shared/models/data_types.py" "shared/models/data_types.py" 2>/dev/null
mv "archive_legacy_20250704/shared/models/function_types.py" "shared/models/function_types.py" 2>/dev/null
mv "archive_legacy_20250704/utils/safe_json_encoder.py" "utils/safe_json_encoder.py" 2>/dev/null

echo "✅ Recovery complete"
